### ISSUE TITLE
Floodplains

### ISSUE THREAD

**Issue by 4xAsh** [SpacedOutChicken/DeCiv-Redux#21]
Floodplains no longer generate in the latest update.
Ily

**Comment by SpacedOutChicken** [comment]
The flood plains disappeared by accident. They're no longer hardcoded the way they were before, and I haven't put anything in to restore them.

That said, I plan on not restoring them, because they seem to give a little too much food, making things too easy for anyone lucky enough to settle next to a river. I'll be replacing them with Swamp tiles, which don't grant any food bonuses.

**Comment by HaneulCheong** [comment]
> The flood plains disappeared by accident. They're no longer hardcoded the way they were before, and I haven't put anything in to restore them.
> 
> That said, I plan on not restoring them, because they seem to give a little too much food, making things too easy for anyone lucky enough to settle next to a river. I'll be replacing them with Swamp tiles, which don't grant any food bonuses.

Seems reasonable; I second this.
